import {
  FilePlus,
  FileMinus,
  FileOutput,
  FileInput,
  RotateCw,
  Images,
  Crop,
  Scissors,
  Minimize,
  VideoIcon,
  Film,
  Music,
  Code,
  FileJson,
  FileCode,
  Archive,
  Folder,
  FolderOpen,
  FileDigit,
  FileSpreadsheet,
  FileType,
  FileImage,
  FileSearch,
  FileWarning,
  ShieldCheck,
} from "lucide-react"
import type { Tool } from "./types"

export const pdfTools: Tool[] = [
  {
    id: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDFs into a single document.",
    icon: <FilePlus className="h-5 w-5" />,
    category: "pdf",
    allowMultiple: true,
  },
  {
    id: "split-pdf",
    name: "Split PDF",
    description: "Separate one page or a whole set for easy conversion.",
    icon: <FileMinus className="h-5 w-5" />,
    category: "pdf",
    allowMultiple: false,
  },
  {
    id: "compress-pdf",
    name: "Compress PDF",
    description: "Reduce file size while optimizing for quality.",
    icon: <Minimize className="h-5 w-5" />,
    category: "pdf",
    allowMultiple: false,
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    description: "Convert PDF files to editable Word documents.",
    icon: <FileOutput className="h-5 w-5" />,
    category: "pdf",
    allowMultiple: false,
  },
  {
    id: "word-to-pdf",
    name: "Word to PDF",
    description: "Convert Word documents to PDF format.",
    icon: <FileInput className="h-5 w-5" />,
    category: "pdf",
    allowMultiple: false,
  },
  {
    id: "pdf-to-excel",
    name: "PDF to Excel",
    description: "Extract data from PDFs into Excel spreadsheets.",
    icon: <FileSpreadsheet className="h-5 w-5" />,
    category: "pdf",
    allowMultiple: false,
  },
  {
    id: "ocr-pdf",
    name: "OCR PDF",
    description: "Convert scanned PDFs to searchable text.",
    icon: <FileSearch className="h-5 w-5" />,
    category: "pdf",
    allowMultiple: false,
  },
]

export const imageTools: Tool[] = [
  {
    id: "jpg-to-png",
    name: "JPG to PNG",
    description: "Convert JPG images to PNG format with transparency.",
    icon: <FileImage className="h-5 w-5" />,
    category: "image",
    allowMultiple: true,
  },
  {
    id: "png-to-jpg",
    name: "PNG to JPG",
    description: "Convert PNG images to JPG format with quality options.",
    icon: <FileImage className="h-5 w-5" />,
    category: "image",
    allowMultiple: true,
  },
  {
    id: "svg-to-png",
    name: "SVG to PNG",
    description: "Convert vector SVG images to raster PNG format.",
    icon: <FileType className="h-5 w-5" />,
    category: "image",
    allowMultiple: true,
  },
  {
    id: "heic-to-jpg",
    name: "HEIC to JPG",
    description: "Convert Apple HEIC photos to widely compatible JPG.",
    icon: <FileImage className="h-5 w-5" />,
    category: "image",
    allowMultiple: true,
  },
  {
    id: "resize-image",
    name: "Resize Image",
    description: "Change image dimensions while preserving quality.",
    icon: <Images className="h-5 w-5" />,
    category: "image",
    allowMultiple: true,
  },
  {
    id: "crop-image",
    name: "Crop Image",
    description: "Remove unwanted areas from your images.",
    icon: <Crop className="h-5 w-5" />,
    category: "image",
    allowMultiple: false,
  },
  {
    id: "compress-image",
    name: "Compress Image",
    description: "Reduce image file size while maintaining quality.",
    icon: <Minimize className="h-5 w-5" />,
    category: "image",
    allowMultiple: true,
  },
  {
    id: "webp-converter",
    name: "WebP Converter",
    description: "Convert to/from WebP format for optimized web images.",
    icon: <FileImage className="h-5 w-5" />,
    category: "image",
    allowMultiple: true,
  },
]

export const videoTools: Tool[] = [
  {
    id: "mp4-to-mov",
    name: "MP4 to MOV",
    description: "Convert MP4 videos to MOV format.",
    icon: <VideoIcon className="h-5 w-5" />,
    category: "video",
    allowMultiple: true,
  },
  {
    id: "mov-to-mp4",
    name: "MOV to MP4",
    description: "Convert MOV videos to MP4 format.",
    icon: <VideoIcon className="h-5 w-5" />,
    category: "video",
    allowMultiple: true,
  },
  {
    id: "avi-to-gif",
    name: "AVI to GIF",
    description: "Convert AVI videos to animated GIF images.",
    icon: <Film className="h-5 w-5" />,
    category: "video",
    allowMultiple: true,
  },
  {
    id: "mkv-to-mp3",
    name: "MKV to MP3",
    description: "Extract audio from MKV videos to MP3 format.",
    icon: <Music className="h-5 w-5" />,
    category: "video",
    allowMultiple: true,
  },
  {
    id: "trim-video",
    name: "Trim Video",
    description: "Cut unwanted parts from your videos.",
    icon: <Scissors className="h-5 w-5" />,
    category: "video",
    allowMultiple: false,
  },
  {
    id: "compress-video",
    name: "Compress Video",
    description: "Reduce video file size while maintaining quality.",
    icon: <Minimize className="h-5 w-5" />,
    category: "video",
    allowMultiple: false,
  },
  {
    id: "rotate-video",
    name: "Rotate Video",
    description: "Rotate videos to the correct orientation.",
    icon: <RotateCw className="h-5 w-5" />,
    category: "video",
    allowMultiple: false,
  },
  {
    id: "video-to-gif",
    name: "Video to GIF",
    description: "Convert any video format to animated GIF.",
    icon: <Film className="h-5 w-5" />,
    category: "video",
    allowMultiple: false,
  },
]

export const audioTools: Tool[] = [
  {
    id: "mp3-to-wav",
    name: "MP3 to WAV",
    description: "Convert MP3 audio to WAV format.",
    icon: <Music className="h-5 w-5" />,
    category: "audio",
    allowMultiple: true,
  },
  {
    id: "wav-to-mp3",
    name: "WAV to MP3",
    description: "Convert WAV audio to MP3 format.",
    icon: <Music className="h-5 w-5" />,
    category: "audio",
    allowMultiple: true,
  },
  {
    id: "flac-to-aac",
    name: "FLAC to AAC",
    description: "Convert FLAC audio to AAC format.",
    icon: <FileDigit className="h-5 w-5" />,
    category: "audio",
    allowMultiple: true,
  },
  {
    id: "ogg-to-m4a",
    name: "OGG to M4A",
    description: "Convert OGG audio to M4A format.",
    icon: <FileDigit className="h-5 w-5" />,
    category: "audio",
    allowMultiple: true,
  },
  {
    id: "cut-audio",
    name: "Cut Audio",
    description: "Trim unwanted parts from your audio files.",
    icon: <Scissors className="h-5 w-5" />,
    category: "audio",
    allowMultiple: false,
  },
]

export const codeTools: Tool[] = [
  {
    id: "json-to-xml",
    name: "JSON to XML",
    description: "Convert JSON data to XML format.",
    icon: <FileJson className="h-5 w-5" />,
    category: "code",
    allowMultiple: true,
  },
  {
    id: "xml-to-json",
    name: "XML to JSON",
    description: "Convert XML data to JSON format.",
    icon: <FileJson className="h-5 w-5" />,
    category: "code",
    allowMultiple: true,
  },
  {
    id: "yaml-to-csv",
    name: "YAML to CSV",
    description: "Convert YAML data to CSV format.",
    icon: <FileCode className="h-5 w-5" />,
    category: "code",
    allowMultiple: true,
  },
  {
    id: "csv-to-yaml",
    name: "CSV to YAML",
    description: "Convert CSV data to YAML format.",
    icon: <FileCode className="h-5 w-5" />,
    category: "code",
    allowMultiple: true,
  },
  {
    id: "minify-js",
    name: "Minify JS",
    description: "Compress JavaScript code by removing whitespace.",
    icon: <Code className="h-5 w-5" />,
    category: "code",
    allowMultiple: true,
  },
  {
    id: "minify-css",
    name: "Minify CSS",
    description: "Compress CSS code by removing whitespace and comments.",
    icon: <Code className="h-5 w-5" />,
    category: "code",
    allowMultiple: true,
  },
  {
    id: "beautify-js",
    name: "Beautify JS",
    description: "Format JavaScript code with proper indentation.",
    icon: <FileCode className="h-5 w-5" />,
    category: "code",
    allowMultiple: true,
  },
  {
    id: "beautify-css",
    name: "Beautify CSS",
    description: "Format CSS code with proper indentation.",
    icon: <FileCode className="h-5 w-5" />,
    category: "code",
    allowMultiple: true,
  },
  {
    id: "beautify-html",
    name: "Beautify HTML",
    description: "Format HTML code with proper indentation.",
    icon: <FileCode className="h-5 w-5" />,
    category: "code",
    allowMultiple: true,
  },
]

export const archiveTools: Tool[] = [
  {
    id: "zip-to-rar",
    name: "ZIP to RAR",
    description: "Convert ZIP archives to RAR format.",
    icon: <Archive className="h-5 w-5" />,
    category: "archive",
    allowMultiple: false,
  },
  {
    id: "rar-to-zip",
    name: "RAR to ZIP",
    description: "Convert RAR archives to ZIP format.",
    icon: <Archive className="h-5 w-5" />,
    category: "archive",
    allowMultiple: false,
  },
  {
    id: "tar-to-7z",
    name: "TAR to 7Z",
    description: "Convert TAR archives to 7Z format.",
    icon: <FolderOpen className="h-5 w-5" />,
    category: "archive",
    allowMultiple: false,
  },
  {
    id: "7z-to-tar",
    name: "7Z to TAR",
    description: "Convert 7Z archives to TAR format.",
    icon: <FolderOpen className="h-5 w-5" />,
    category: "archive",
    allowMultiple: false,
  },
  {
    id: "compress-files",
    name: "Compress Files",
    description: "Compress multiple files into a single archive.",
    icon: <Folder className="h-5 w-5" />,
    category: "archive",
    allowMultiple: true,
  },
  {
    id: "extract-files",
    name: "Extract Files",
    description: "Extract files from various archive formats.",
    icon: <FolderOpen className="h-5 w-5" />,
    category: "archive",
    allowMultiple: false,
  },
  {
    id: "password-protect",
    name: "Password Protect",
    description: "Add password protection to your archives.",
    icon: <ShieldCheck className="h-5 w-5" />,
    category: "archive",
    allowMultiple: false,
  },
  {
    id: "repair-archive",
    name: "Repair Archive",
    description: "Fix corrupted or damaged archive files.",
    icon: <FileWarning className="h-5 w-5" />,
    category: "archive",
    allowMultiple: false,
  },
  {
    id: "split-archive",
    name: "Split Archive",
    description: "Split large archives into smaller parts.",
    icon: <FileMinus className="h-5 w-5" />,
    category: "archive",
    allowMultiple: false,
  },
]

// Helper function to get a tool by ID
export function getToolById(id: string): Tool | undefined {
  return [...pdfTools, ...imageTools, ...videoTools, ...audioTools, ...codeTools, ...archiveTools].find(
    (tool) => tool.id === id,
  )
}

